### ISSUE TITLE
Issue with pinning

### ISSUE THREAD

**Issue by Riverface** [MontagueMGM/shape_keys_plus#3]
When you pin an object into the Properties panel, Shape keys Plus no longer has a menu in the mesh tab, nor does regular shape keys. This slows the workflow down really bad.

**Comment by MontagueMGM** [comment]
I was using the `active_object` attribute instead of `object`, thinking they were the same. As it turns out, `object` is the one that keeps track of the pinned object even when another one becomes active. This should be fixed now in the 1.3.4 patch.

Keep in mind you have to pin the **Object Properties** and not the **Object Data Properties**, since the former is the one used to access shape key data, even though the Shape Keys _panel_ is shown in the latter.

**Comment by Riverface** [comment]
Thank goodness, I thought you were done updating this thing and I'd have to learn python.
It's a great addon. Thank you for your quick response, I'll check that patch out.

**Comment by MontagueMGM** [comment]
The add-on in its current state is very messy - I don't recommend looking into it. I've been working on a v2.0 overhaul in my spare time that, among other things, cleans up the code and properly separates it into multiple files and packages. The full changelog is going to take a lot of planning and testing but I can't rush it. In the meantime, v1.3 will still get patches as soon as I'm notified of any issues.

**Comment by Riverface** [comment]
It's a really good addon anyway! Would you be ok with hearing feature suggestions?

**Comment by MontagueMGM** [comment]
That's fine, just post another issue listing your suggestions and give it the "enhancement" label.
