### ISSUE TITLE
Feature: Negative value for "show active shapes" threshold

### ISSUE THREAD

**Issue by Fak3** [MontagueMGM/shape_keys_plus#7]
Currently only positive value can be entered in the threshold input, so the shape key with negative value can't be easily filtered with this.

**Comment by MontagueMGM** [comment]
The arrow to the right of the threshold flips the filter direction so that only values lower than the threshold are visible. The 0.0|1.0 range in the threshold is only a soft limit, meaning it just prevents you from dragging past those values. It still allows you to type a negative number since I didn't make 0.0 a hard minimum.

The hard limits for a shape key's value in Blender are -10.0|10.0, but it would be inconvenient to standard use if I used those as the threshold's soft limits.
